os:
  - linux
  - osx
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to run tests
<<<<<<< HEAD
script: python setup.py install
=======
script: make test
>>>>>>> 9e723a0e6f0b966b71534398d211bc4fec018650
